-- AlterTable
ALTER TABLE "cars" ALTER COLUMN "length" SET DATA TYPE TEXT,
ALTER COLUMN "width" SET DATA TYPE TEXT,
ALTER COLUMN "height" SET DATA TYPE TEXT,
ALTER COLUMN "seating_capacity" SET DATA TYPE TEXT,
ALTER COLUMN "fuel_tank_capacity" SET DATA TYPE TEXT;
